### ISSUE TITLE
Activate param to cache multiple scenarios in transition

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/transition#1023]
Needed for Long Distance surveys with different regions/scenarios active at the same time

**Comment by greenscientist** [comment]
@tahini @kaligrafy 

To configure this, should we add a config entry to the config.js file or another environment variable ?

**Comment by tahini** [comment]
@greenscientist good question, that would be a per-deployment feature, for specific use cases (or else we may bust the memory). So maybe env?

**Comment by greenscientist** [comment]
@tahini Yes per deployment to save on memory. 
But I can as easily configure the config file or add an env variable.

**Comment by greenscientist** [comment]
I'm starting to get a bit annoyed at the amount of stuff we have as env variable. Things like credentials makes sense, but we have a lot of config in there too that I don't know if they should be elsewhere. But we have not yet refactor our configuration/preference management, so question mark here.

**Comment by tahini** [comment]
ftr, I will not block a PR for either.

It can go in the config, at least we can eventually type it and access it more easily.

**Comment by tahini** [comment]
@greenscientist from your questions, do we assume you are assigning yourself to this issue?
