### ISSUE TITLE
routing: The `Routing`.`calculate` function should query all modes in parallel

### ISSUE THREAD

**Issue by tahini** [chairemobilite/transition#1028]
Currently, for each mode, we create a result object, where we await the result. Which means all modes are done sequentially instead of in parallel. We should make them parallel, especially that each mode makes a call to a different routing server.

The function is in `chaire-lib-backend/src/services/routing/Routing.ts`

**Comment by tahini** [comment]
@greenscientist si tu as du temps à optimiser...

**Comment by greenscientist** [comment]
Did the code and ran some benchmarks. Currently, what takes the most time is the transit calculation. All the other ones are OSRM call which are quite fast. Would still be worth it to do, but the gain is minimal. Maybe about a second in saving.
