### ISSUE TITLE
socket.io: Uncaught Error: got plaintext data when reconstructing a packet

### ISSUE THREAD

**Issue by tahini** [chairemobilite/transition#1058]
On many of our instances, I get this error this error while loading the page. The dashboard does not work. It is stuck at the loading node part, then the socket disconnects. It was not like that before.

The only instance that seems to still work is MTQ.

This is with firefox on Linux.

**Comment by kaligrafy** [comment]
I do not get the error on macos using Chrome on any instance.

**Comment by tahini** [comment]
It works this morning, not sure what happened yesterday...

**Comment by tahini** [comment]
Turns out the problem was my home switch (which is causing all kinds of smallish network problems like that). So transition or socket.io are not to blame, it's the network. From the wifi, it works fine...
