### ISSUE TITLE
transition: manage link with latex definitions and symbols

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/transition#136]
[Repo](https://github.com/kaligrafy/CIV6708-Definitions-and-symbols/blob/master/main.tex)

**Comment by GabrielBruno24** [comment]
@kaligrafy Can you confirm that this the issue that https://github.com/chairemobilite/transition/pull/1094 is solving?

**Comment by kaligrafy** [comment]
Ye, that's it!
