### ISSUE TITLE
transition: Accessibility Map: exception with some delta durations

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/transition#169]
<img width="641" alt="Screen Shot 2021-01-20 at 13 52 17" src="https://user-images.githubusercontent.com/879608/105222049-f0fe9380-5b27-11eb-90c8-61ccc025c8c2.png">

**Comment by tahini** [comment]
I have no idea what I'm supposed to do with this issue. It's probably not there anymore? @kaligrafy if you remember, please add more details

**Comment by kaligrafy** [comment]
Let's close until we find if it happens again or not
