### ISSUE TITLE
transition: exception: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by greenscientist** [chairemobilite/transition#175]
While trying to edit a new line

Cannot read property 'length' of undefined
    in r
    in div
    in n
    in e
    in withI18nextTranslation(e)
    in div
    in section
    in mb
    in div
    in section
    in n
    in withI18nextTranslation(n)
    in component
    in e
    in Unknown
    in S
    in e
    in Vx
    in e
    in o
    in u

**Comment by tahini** [comment]
@greenscientist Can we close this issue as unclear, old and probably fixed?

**Comment by tahini** [comment]
Given the no answer, we'll consider it as fixed

**Comment by greenscientist** [comment]
I guess, we just need to have way more error checking in all the stack!
