### ISSUE TITLE
Refactor OSRM Service manager, to support many options

### ISSUE THREAD

**Issue by tahini** [chairemobilite/transition#19]
- [x] Bring the OSRM Service and its manager to the typescript workspace.

- [ ] Refactor the code so it can support many ways to run osrm backend (for example local, remote, docker)

**Comment by greenscientist** [comment]
@tahini, do we have an issue to run OSRM in docker instead of natively or remote?

**Comment by tahini** [comment]
yes #20

**Comment by tahini** [comment]
And #16 and #46? So yeah, I think docker is pretty well covered ;-)

**Comment by greenscientist** [comment]
haha, ok, I should have searched...
