### ISSUE TITLE
transition: default filling of fields when importing batch CSV for routing

### ISSUE THREAD

**Issue by matrep** [chairemobilite/transition#209]
When importing a multiple routing file, it would be nice to fill the field names by default, especially if the format is the same than the exported CSV (id, lat, long, etc.)
![fill](https://user-images.githubusercontent.com/19364997/110499539-569de380-80c6-11eb-8cc0-0e8fe0f0f46f.jpg)

**Comment by tahini** [comment]
This is fixed
