### ISSUE TITLE
Add types to transition-app/chaire-lib/backend/src/utils/osrm/OSRMService.ts

### ISSUE THREAD

**Issue by greenscientist** [chairemobilite/transition#283]
I don't know if you just wanted to quickly move this class to typescript, but it would be easy-ish to type those values. See the OSRMRoutingService in chaire-lib/common for an example, there's an `@types/osrm` package which contains all the types of the osrm-backend server, which you can use.

If you don't plan to do it now, please add an issue in the open source milestone, so we don't delay this too much

_Originally posted by @tahini in https://github.com/kaligrafy/transition/pull/1014#discussion_r688766918_

**Comment by tahini** [comment]
The types are all fine now
