### ISSUE TITLE
transition: titre manquant « Nœuds d'arrêts » en cliquant sur le menu des nœuds d'arrêts

### ISSUE THREAD

**Issue by stmsim** [chairemobilite/transition#308]
L'ouverture de chacun des menus à gauche nous permet de retrouver le titre dudit menu, accompagné d'un symbole approprié, à droite. 

Exemple pour le menu des agences : 
![image](https://user-images.githubusercontent.com/86686508/137323521-d4d6e2d4-b16e-489f-b43b-7e73ad28df6d.png)

Cependant, il manque le titre pour le menu des nœuds d'arrêts. Je suggère donc qu'il soit ajouté.

![image](https://user-images.githubusercontent.com/86686508/137323822-138b2940-8ff2-4825-9b42-9a7779b5c2a5.png)

**Comment by kaligrafy** [comment]
Already fixed
