### ISSUE TITLE
transition: schedules disappear when saving line

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/transition#366]
How to reproduce:
- Create a schedule for a line, choose the number fo vehicles, then generate and save schedule, the number of trips appear correctly
- Save the line and reopen it, it shows 0 trips and the schedule don't exist anymore.

Note: does not happen every time, seems to be isolated, but really annoying!

**Comment by tahini** [comment]
This hasn't happened in ages, it should be fixed now that schedules are better handled
