### ISSUE TITLE
Test support for Node 18 and 20

### ISSUE THREAD

**Issue by greenscientist** [chairemobilite/transition#421]
Node 16 EOL is 2023-09-11
https://nodejs.org/en/blog/announcements/nodejs16-eol/

Node 18 is LTS until 2025, so that will give us plenty of support.

**Comment by kaligrafy** [comment]
Node 20 too

**Comment by greenscientist** [comment]
We are past EOL, we'll need to upgrade things to at least node 18

**Comment by tahini** [comment]
Done
