### ISSUE TITLE
Upgrade docker base containers

### ISSUE THREAD

**Issue by tahini** [chairemobilite/transition#423]
Some of the docker container dependencies are getting old, which prevents us from moving forward with some latest versions (like some rust packages).

We should upgrade to more recent versions.

cc @greenscientist

**Comment by tahini** [comment]
@greenscientist Did we fix this? Can use update the json2capnp command line args?

**Comment by greenscientist** [comment]
No, the json2capnp changes would require something newer than bullseye. 
(I'll check if we could run a bookworm binary on bullseye.)
