### ISSUE TITLE
Resolve unlicensed dependencies issues

### ISSUE THREAD

**Issue by tahini** [chairemobilite/transition#439]
There are 3 unlicensed dependencies in the project. Some have licenses now, but had not with the package version used. Maybe upgrading these packages can fix this.

We should try to see if we can really resolve these dependencies before ignoring them.

**Comment by tahini** [comment]
PR #473 fixes some issues.

For buffer, we use jszip instead of unzipper. We already depend on jszip anyway.
For cycle, we use inquirer instead of prompt. Almost all tasks use inquirer. Only create-user used prompt, so it's not necessary.

Unfortunately, for @mapbox/jsonlint-lines-primitives, there is no way to not use it as long as we use mapbox-gl-js, which won't be dropped in a foreseeable future (or will it?...)

**Comment by greenscientist** [comment]
We know we want to drop mapbox, so we at least know the path to fixing that one. We could mark it as "fine" in fossa for the time being.

**Comment by tahini** [comment]
The last issue was marked as ignored in fossa
