### ISSUE TITLE
How to manage our database migrations?

### ISSUE THREAD

**Issue by tahini** [chairemobilite/transition#442]
In the legacy, there was one migration directory, which contains tables for transition, evolution, osc2ar and octavi. The easy migration path is to just take it all in this repo now. But we have tables for evolution, osc2ar and octavi that are not necessary.

But if we only migrate related migrations, we get errors in current databases for the missing migrations.

Also see this https://stackoverflow.com/questions/57174914/knex-js-can-i-have-multiple-migrations-to-save-in-only-one-migration-table 

We could have multiple migration tables for each project: chaire-lib, transition, evolution and octavi/osc2ar migrations. Or the post suggests that each project could have its own database (or schema) with their own migrations. That means chaire-lib would be responsible for the users table. Transition and Evolution are quite different, but osc2ar and octavi need some transition stuff and they are more or less related.

So what do we do?

1. Single database, multiple migrations tables
2. Multiple databases for the application

Maintenance-wise, would 2 be more complicated? By the time a single application requires data from more than one app at a time, we probably will have some micro-service architecture to get data from the appropriate location...

cc @kaligrafy @greenscientist  thoughts?

**Comment by greenscientist** [comment]
I think we should consider this new repo as a new app and drop all the old migration script and start new. 

If people have been running a legacy app, they would need to upgrade with the legacy app and then migrate to the public app. (We don't have many internal users, so we can deal with that easily.

**Comment by tahini** [comment]
I'm not sure how I went from A to B, but I think your comment implies the 1- approach above (multiple migration tables (one per package) in a single database _if_ the "web application" contains more than the). We add one migration, which adds the new migration table, adds the migrations, then drops the old table...

**Comment by greenscientist** [comment]
btw, yeah, multiple database would be awful. 
My thought: each application should be responsible for their migration. They could import something from chaire-lib to do the "common" bits. But some how the responsabilités will reside in the app.
