### ISSUE TITLE
Procédure d'installation

### ISSUE THREAD

**Issue by brodyFlannigan** [chairemobilite/transition#454]
Bonjour!

Je suis TELLEMENT content que Transition soit finalement en open source! C'est un outil super prometteur!

Je me demandais quelles instructions je dois suivre pour installer Transition afin de pouvoir m'en servir (pas pour développer). J'ai trouvé plusieurs listes d'instructions différentes mais je n'arrive pas à trouver des instructions de A à Z pour installer et partir Transition sur Linux. Serait-il possible de m'éclairer un peu? (Des instructions en anglais conviennent parfaitement!)

Merci!

**Comment by kaligrafy** [comment]
Bonjour! @tahini et @greenscientist sont justement en train de préparer le repository pour le mettre open source, mais ce n'est pas encore terminé. Il reste beaucoup de documentation à ajouter aussi. On fait le plus vite possible!

**Comment by brodyFlannigan** [comment]
Super! Merci Pierre-Léo.

**Comment by tahini** [comment]
Bonjour @brodyFlannigan ! En effet, nous sommes en train de mettre en ordre ce nouveau repo pour l'open source. Et il manque encore un point d'entrée unique pour démarrer. Je dirais qu'à date, ce qui ressemble le plus à des instructions pour être fonctionnel avec Transition sur Linux sont ici https://github.com/chairemobilite/transition/tree/main/examples (avec lien vers la doc d'installation complète).

Vos commentaires sont bienvenus en tant que nouvel utilisateur/installateur! Dites-nous s'il manque de l'info, si ce n'est pas clair, si c'est mal présenté, etc. Mais d'ici une semaine ou deux, ça devrait être pas mal mieux.

**Comment by tahini** [comment]
@brodyFlannigan La PR #470 met à jour la documentation pour que le README de départ soit suffisant pour installer Transition et avoir une instance fonctionnelle. Si ça vous dit, pourriez-vous en faire une revue pour voir si c'est suffisant? et nous faire part de tout commentaire pouvant nous aider à l'améliorer. Merci!

**Comment by brodyFlannigan** [comment]
Allô! Merci pour le suivi.

Je vais laisser mes commentaires directement dans la #470 🙂
