### ISSUE TITLE
Add an API to access transition's functionality externally

### ISSUE THREAD

**Issue by tahini** [chairemobilite/transition#479]
For now, we need to access the interface the run tasks or do operations on Transition. It would be nice to be able to script the interactions with Transition, to make manipulations completely reproducible, for research purposes, for example through a python script.

**Comment by tahini** [comment]
@hverreault Pourrais-tu ajouter un pseudo-code de ce que tu aimerais pouvoir scripter dans un premier temps, pour nous aider à partir cet API?  

@adolmajian avait aussi mentionné de l'intérêt pour une telle fonctionnalité.

**Comment by tahini** [comment]
Ah ben dis donc! On avait un issue pour ça! C'est maintenant fait, 
voir https://github.com/chairemobilite/transition/tree/main/pyTransition et https://chairemobilite.github.io/transition/

**Comment by greenscientist** [comment]
Faudrait ajouter ces liens dans le readme principal.
