### ISSUE TITLE
Revisit our node minimal version

### ISSUE THREAD

**Issue by tahini** [chairemobilite/transition#480]
I just tried running node 12.9, our minimal version, and by chance, tried the downloadOsmNetworkData task and got `Error: Cannot find module 'node:stream'`. Node 16 works fine. We should maybe update our minimum requirement?

**Comment by greenscientist** [comment]
I think that's a good idea. Node-16 is already a bit old anyway

**Comment by tahini** [comment]
So 16 as minimal version would be ok? Everyone agrees?
