### ISSUE TITLE
Docker: First user creation

### ISSUE THREAD

**Issue by brodyFlannigan** [chairemobilite/transition#498]
Hi!

I am looking at installing Transition via Docker to avoid issues with dependencies needing to be installed seperately.
The only thing preventing me from going ahead with this is that I'm not sure how I need to create the first user, as there is a procedure in the "regular" install documentation but no mention of this in the docker procedure.

Would you be able to clarify how I can create the first user in the docker version?

Thank you!

**Comment by tahini** [comment]
@brodyFlannigan You should be able to create the user from the interface, by navigating to http://localhost:8080. There's a register link at the bottom of the login page. The command line create-user is not required, unless you want to create an admin user (for now), but in Transition, the admin user doesn't have any extra privileges.

But I never tried running Transition locally from docker, @greenscientist may have more information on this.

**Comment by brodyFlannigan** [comment]
It works!
