### ISSUE TITLE
Schedules: Batch add schedules for a service at x minutes

### ISSUE THREAD

**Issue by tahini** [chairemobilite/transition#526]
Say we want to generate schedules at every X minutes for a set of lines.

It should be possible to batch select lines and generate a schedule at interval X, associated with a service.

The selected lines should not have a schedule already defined for the service. Otherwise, ask the user to confirm if he wants to override the current schedule.

**Comment by greenscientist** [comment]
Is this the same as #292 ?

**Comment by kaligrafy** [comment]
DUplicate of #292
