### ISSUE TITLE
Improve OSRM mode/ports management (code, configs, etc)

### ISSUE THREAD

**Issue by greenscientist** [chairemobilite/transition#53]
@tahini have highlighted a few inconsistencies and improvement around the OSRM modes configurations and management. 
We probably want to revisit those that we not addressed since they add a  too big scope for that PR. 
Eventually, we might want to move out the process management of OSRM outside of the Transition code base

**Comment by tahini** [comment]
@greenscientist Do you think your addition of the OSRMMode fixed this issue?

**Comment by greenscientist** [comment]
Yeah, I think we can consider this is covered
