### ISSUE TITLE
chaire-lib-frontend FrontendUser should be renamed and moved to common

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/transition#630]
In evolution, the user could be used in helpers and validations/conditional, which are now included in evolution-common, so chaire-lib should have a user class usable in both backend and frontend.

**Comment by tahini** [comment]
Indeed the user permissions are required for some use cases, so instead of FrontendUser, we can call it CliUser, for any client-side application. Tasks and other api calls could also make use of it.
