### ISSUE TITLE
Services filter not working as expected during GTFS import

### ISSUE THREAD

**Issue by adolmajian** [chairemobilite/transition#674]
The option "Filtrer pour une période" is not working properly. See screenshots below.

Actual content of calendar.txt
![image](https://github.com/chairemobilite/transition/assets/1723914/a37cc8f5-0bd5-4a0c-8918-64decca2aca7)

List of service ids without any filters (it matches the raw text file)
![image](https://github.com/chairemobilite/transition/assets/1723914/ca52021f-d26d-4015-ad89-2b604219b643)

List of service ids when applying filter for 2021-10-16 to 2021-10-22
![image](https://github.com/chairemobilite/transition/assets/1723914/7afd72f9-136b-43ee-a0ca-1505ec93dc05)
The weekend services do not appear in the filtered list.

**Comment by greenscientist** [comment]
@adolmajian Can you provide a link to the GTFS file that you are using? That would facilitate testing

**Comment by tahini** [comment]
Indeed, I cannot reproduce with any of the GTFS I have with similar data (EXO's gtfs) and unit tests show this should work, so @adolmajian if you could provide the GTFS. The problem may be elsewhere. Is there a calendar_dates.txt file that may filter out the services?

**Comment by tahini** [comment]
This is a bug. The only dates in calendar_dates.txt are considered as the only dates the service is available and does not consider the days of service in calendar.txt.
