### ISSUE TITLE
chairelib: add an interface to import zones and polygons

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/transition#689]
Will be used in evolution and surveys also to set SDR and/or SM for each home/visited places locations

**Comment by tahini** [comment]
Zones are a concept that we have in many of our applications. It is currently implemented in octavi. A set of zones is a data source. Zones are more generally polygons associated with a datasource.

In chaire-lib, we could have the backend: import from geojson, database queries, types, etc.

The frontend part, though, has many sides: chaire-lib-frontend will provide widget components to list the available zone data sources and import them. 

More than that could be application specific. For example, in an evolution survey, only admins or certain roles could import zones from the admin menu. In Transition, this feature could be made available to all users, no matter their roles and could be used for filtering or other.

This issue concerns only the shared chaire-lib part.
