### ISSUE TITLE
Rewrite zip extraction code to use Buffer in upload.socketRoutes.ts

### ISSUE THREAD

**Issue by greenscientist** [chairemobilite/transition#691]
The code in packages/transition-backend/src/api/upload.socketRoutes.ts extract the zip file by read all the content into a variable in memory and then writing the content in a file. 
We should be using buffers in this case, to not reach the variable size limit and save some memory. 
We could also switch to a package which does it completely transparently.

**Comment by greenscientist** [comment]
Random blog post: https://blog.logrocket.com/best-methods-unzipping-files-node-js/

**Comment by davidmurray** [comment]
@greenscientist  What if we instead just used the standard `zip` and `unzip` unix commands? All we are really doing in the code is zipping a directory or unzipping an archive to a directory. Nothing that can't be done with a one line `zip` or `unzip` call.
Plus, we would drop the dependency on a library, `JSZip`.
What do you think? cc @tahini  @kaligrafy

**Comment by greenscientist** [comment]
@davidmurray, we usually don't know what is installed on the system. Also, the code can run on any OSes. We sould need to add this as a requirement in the installation. 
the zip algoritgm is simple enough that it's easy to use in via a library.

**Comment by davidmurray** [comment]
good point
I'll rewrite the code to use https://www.npmjs.com/package/node-stream-zip then
