### ISSUE TITLE
batchRouting: trRouting is sometimes left in defunct state

### ISSUE THREAD

**Issue by tahini** [chairemobilite/transition#709]
I've seen it locally once or twice and it happens on the server too, trRouting remains defunct, so all batch queries after have errors becuse trRouting cannot be started as it is considered as still running but it doesn't answer...

No idea why, the trRouting's last logs don't show anything. And so much happened on the server that logs from that moment are lost.

**Comment by greenscientist** [comment]
Cannot be started from the Transition perspective or because the socket cannot be bind to?

**Comment by greenscientist** [comment]
One "short term" solution would be to check the state of the process pointed by the PID file and wipe the file if the process is defunct. That should allow for a restart.

**Comment by greenscientist** [comment]
Might be related to issues like https://github.com/chairemobilite/trRouting/issues/255

**Comment by greenscientist** [comment]
Yes, that's what I meant. The defunct state is probably cause by some race condition during a crash or something like that.

**Comment by greenscientist** [comment]
Log potentiellement du process defunct
[trRouting.log](https://github.com/chairemobilite/transition/files/15041370/trRouting.log)

**Comment by tahini** [comment]
À noter aussi le flux haut niveau de ce qui a été fait sur Transition au moment où cette situation s'est produite:

```
1. Supprimé la tâche en cours
2. Annulé la même tâche en cours en me disant que j'aurais peut-être dû faire ça en premier avant de la supprimer
3. Supprimé des [lignes]
4. Mis à jour le cache
5. Démarré un nouveau calcul multiple
```

**Comment by greenscientist** [comment]
Y'a peut-etre quelque chose dans la séquence suppression/annulation qui mêler Node.js et qui l'empeche d'acknowledger son child

**Comment by greenscientist** [comment]
A thought: when we cancel a batch calculation we need to kill the running trRouting. But maybe we have some request still in flight. We might need to first stop the calculation, maybe sure we terminate all in flight request before we go and kill trRouting. If we kill trRouting first, maybe we leave some socket in a weird state. (Should not happen, but we never know)

**Comment by greenscientist** [comment]
I think that the p-queue.clear() on cancellation is too  agressive in TrRoutingBatch:
                    if (this.options.isCancelled()) {
                        promiseQueue.clear();
                    }
This will immediately empty the queue, then the await onIdle will return. Some pending query might still be pending, we might then kill trRouting before those queries are done.

**Comment by greenscientist** [comment]
ok, I don't see anything that we could do with the p-queue directly. 
What we could do instead: use a read/writer lock. That the read lock before the call to odTripTask, release in the finally, and then before calling stopBatch we can attempd to take the write lock, which would block on all the current request to finish before taking it. 
Ok, yes, we can probably just have a "running" counter and check that it's zero before doing the stopBatch. Not sure how to await on this check.

**Comment by tahini** [comment]
Problem happened again, and again, just after job cancellation.
