### ISSUE TITLE
auth: Anonymous login name may already exist in the database

### ISSUE THREAD

**Issue by tahini** [chairemobilite/transition#711]
The anonymous login name takes a random 6 digits number and adds it as username, but that name may already exist in the database. It should try again, or make sure it doesn't exist before saving. We may also use letters instead of numbers to have more choices. Surveys may have a high number of anonymous users and chances of clash are higher

**Comment by millette** [comment]
J'aime bien https://github.com/ai/nanoid pour ça.

On peut [calculer le risque de collision](https://zelark.github.io/nano-id-cc/), par exemple avec l'alphabet ```23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz``` (j'ai enlevé ```0Oo1lI``` pour réduire le risque de confusion), un code de **8 caractères**, à **200 IDs par heure** (70,000 IDs sur 2 semaines), il faut **290 jours** pour un risque de **1% de collision**.

**Comment by tahini** [comment]
Merci pour l'info. Dans la PR proposée, j'utilise les 10 derniers caractères hexadécimaux d'un uuid (on utilise déjà beaucoup cette librairie) et on check jusqu'à 10 fois si l'utilisateur existe. Selon le calculation de collision, ça devrait prendre 1 480 000 logins anonyme pour que cette approche ait 1% de chance de collision. Un risque acceptable je pense. Si on dépasse ça, on ira avec l'alphabet entier!
