### ISSUE TITLE
GTFS: Add the possibility to infer frequency-based schedule upon import

### ISSUE THREAD

**Issue by tibobliss** [chairemobilite/transition#718]
If a route is edited, the changes are not reflected in the exported GTFS `stop_times.txt` file.

Steps to reproduce the problem:

1. Import a GTFS feed
2. Edit a route by adding/removing a node
3. Click all three update buttons in the top right button
4. Export GTFS feed

Here is the result of a randomly selected `trip_id` in the exported `stop_times.txt`. In this case, 6 stops were removed from the route.

![image](https://github.com/chairemobilite/transition/assets/5404176/733d76cc-a222-4ec1-aca1-98fbe6a93aa9)

The `stop_id` column reflects the edited route, but the `arrival_time` and `departure_time` columns are identical to the imported GTFS and do not reflect the modifications made to the route.

Here are the steps needed to export a proper GTFS:
1. Import a GTFS feed
2. Edit a route by adding/removing a node
3. Click all three update buttons in the top right button
4. Generate a new schedule for the route
5. Click all three update buttons again, just in case
6. Update route statistics ![image](https://github.com/chairemobilite/transition/assets/5404176/193da4c1-0c0b-4a1d-9922-14a185210f12)
7. Export GTFS feed

**Comment by tibobliss** [comment]
Here is the expected behavior:

ADDING A NODE
1. Import a GTFS feed
2. Edit a path by adding a new node past the last node, thereby extending the path
3. Save changes
4. Receive prompt asking if we want to update the schedule or keep the existing one
5. Select _Update schedule_
6. Click the update buttons
7. Export GTFS
8. Open _stop_times.txt_
9. A new line has been added to the _stop_times_ for every trip on the modified path and the _arrival_time_ and _departure_time_ are updated to reflect the changes.

REMOVING A NODE
1. Import a GTFS feed
2. Edit a path by removing a node in the middle of the path
3. Save changes
4. Receive prompt asking if we want to update the schedule or keep the existing one
5. Select _Update schedule_
6. Click the update buttons
7. Export GTFS
8. Open _stop_times.txt_
9. A line has been removed from the _stop_times_ for every trip on the modified path and the _arrival_time_ and _departure_time_ are updated to reflect the changes.

**Comment by tibobliss** [comment]
Here is another example of the current behavior when removing or adding stops to a line imported from a GTFS feed.

![image](https://github.com/chairemobilite/transition/assets/5404176/3c6b645e-be47-45c3-aa9b-45e43d2a4282)

**Comment by tahini** [comment]
@tibobliss  Ce qui arrive, c'est que lors de changement à un path, tous les hotaires l'utilisant sont recalculés (donc selon l'intervalle et/ou le nombre d'unités, tous les trips sont réinitialisés).

Or, lorsqu'importé de GTFS, on n'a que des trips, sans les autres paramètres des horaires, donc ça ne recalcule pas.

Quel serait le comportement attendu dans ce cas-ci? 


1. Mettre à jour uniquement les trips utilisant le trajet modifié, au risque de tout bousiller la synchronisation existante dans les horaires? Genre si un bus fait des allers/retour et qu'on ajoute 3 noeuds à l'aller, l'horaire du retour ne permettra plus cette synchro. Comme dirait @kaligrafy ça va faire de la bouette.
2. Informer l'utilisateur qu'il manque de l'information pour pouvoir générer des horaires correctement pour la modification (mais l'idée de base était justement d'éviter d'aller éditer ces horaires manuellement, donc j'imagine que c'est un no-go)
3. Inférer l'intervalle/nombre d'unités/début de la période / fin de la période à partir des trips existants et générer des horaires selon ces données inférées, qui ne permettront par contre par de variabilité à l'intérieur d'une période (s'il infère des trajets au 10 minutes en 6 et 9, ce sera ça, pas de 12 minutes ou 8 minutes entre certaines heures). Ceci devrait par contre être fait à l'import GTFS.
4. d'autres idées?

**Comment by tahini** [comment]
@kaligrafy le temps sous congestion est en effet désirable, mais c'est un autre problème qui n'a pas vraiment de lien avec le problème actuel. En fait, ce problème-ci reste entier, même si on a des données sous congestion.

**Comment by kaligrafy** [comment]
Oui et non, car si on a des données réalistes de congestion et des ratios, on peut recalculer les trajets quand on importe le GTFS et ajuster les ratios pour que ça soit équivalent à l'horaire planifié GTFS. Comme ça si on ajoute des arrêts, ça suit le même ratio par défaut au lieu de prendre l'écoulement libre.

**Comment by tahini** [comment]
Le problème décrit dans le commentaire est pour l'autre trajet, celui qui n'a pas été modifié et qui était peut-être synchronisé avec le trajet modifié (ou pas), et qui ne sera plus synchro, car il va garder son horaire original.

Mais oui, c'est certain qu'en date d'aujourd'hui, le trajet qui serait recalculé le sera en écoulement libre, mais toute amélioration au calcul du trajet se reflètera ici.

**Comment by tahini** [comment]
To fix this issue, we will add an option during GTFS import to generate frequency-based schedules that can be updated. If the option is selected, it will be an approximation of the GTFS service, but for planning purposes may be easier to use to compare the effects of path/schedule changes.

For each period, we will take the average frequency (asymetrical lines may need to be split for better results) and the most commonly used path.

If not selected, the trips will be imported as currently, but it won't be possible to update the schedules if for example, a path is updated. See #852 for this case.

**Comment by tibobliss** [comment]
@tahini Voici les petits hics qu'on a rencontré en faisant cette procédure manuellement, si ça peut t'aider.

Pour que le nombre de départs soit égal à l'horaire de référence et que le premier et le dernier départ coïncident avec les valeurs réelles:

POUR CALCULER L'INTERVALLE
- S'il y a >1 départs durant la période, il faut calculer l'intervalle de la manière suivante pour que le premier et le dernier départ générés correspondent aux balises données: (heure_dernier_départ - heure_premier_départ) / (nombre_départs - 1). Si on ne soustrait pas 1, l'intervalle sera calculé comme si la borne supérieure n'était pas un départ.
- S'il y a seulement 1 départ, un intervalle de 60 secondes fonctionne (mais voir mise en garde plus bas)

POUR GÉNÉRER L'HORAIRE
- L'heure du dernier départ doit être incrémentée d'une minute, sinon Transition ne génèrera pas un départ à l'heure observée du dernier départ. 
- Pour 1 départ à 4:45, par exemple, il faut donner les valeurs suivantes: premier départ à 4:45, dernier départ à 4:46, intervalle de 60 secondes. Cela génère un départ à 4:45.
- Pour 2 départs avec un intervalle de 30 minutes, par exemple, il faut donner les valeurs suivantes: premier départ à 5:00, dernier départ à 5:31, intervalle de 1800 secondes. Cela génère un départ à 5:00 et un à 5:30. Si on met la valeur du dernier départ à 5:30, Transition ne générera qu'un seul départ à 5:00.

**Comment by tibobliss** [comment]
En fait, la valeur du champ _Dernier départ_ devrait être une borne inclusive et pas exclusive, puisqu'elle représente une valeur qui doit se retrouver dans l'intervalle.
