### ISSUE TITLE
auth: remove trailing space in email on login forms

### ISSUE THREAD

**Issue by tahini** [chairemobilite/transition#720]
Some autocomplete software automatically add a space after the email, and the field says the email is invalid. 

See https://github.com/chairemobilite/od_mtl_2023/pull/1187 for a fix in surveys, which can be added in the email fields here too

**Comment by tahini** [comment]
@davidmurray, if you wish to look at this

**Comment by davidmurray** [comment]
> @davidmurray, if you wish to look at this

oui! je peux pas m'assigner l'issue mais je vais investiguer ça
