### ISSUE TITLE
Move forward, save and delete form buttons to the top right

### ISSUE THREAD

**Issue by davidmurray** [chairemobilite/transition#757]
Since the buttons are currently at the bottom, we must scroll all the way down

![image](https://github.com/chairemobilite/transition/assets/545502/649a5b1d-9e9d-4818-8217-05665aa43af0)

I propose we move them at the top to make them more accessible

**Comment by greenscientist** [comment]
Should we have them at both location? Or have them "floating" so that we always see them?

**Comment by davidmurray** [comment]
Oh! floating is a good idea. I'll add them to the header and make that floating so that it's always at the top when scrolling
