### ISSUE TITLE
Add unit conversion react components

### ISSUE THREAD

**Issue by davidmurray** [chairemobilite/transition#775]
Transition displays distances and time durations in many places.
If these values are small, it usually makes more sense to display in meters and seconds.
However, when the values get big, kilometres and minutes (or hours) are usually more appropriate. We could have some react components that automatically convert the values to the best unit for display. 

Here are a few examples where a better unit could improve legibility:

1. Layover should be in minutes if > 60s
![image](https://github.com/chairemobilite/transition/assets/545502/472a8e08-a253-4a54-9fa6-08d342b77301)

2. Cumulative distance should switch to kilometres if > 1000 m:
![image](https://github.com/chairemobilite/transition/assets/545502/b861c5f4-61d3-4fd1-bc8e-b088489d1167)

3. Transit routing results (here it should be in hours and kilometres)
![image](https://github.com/chairemobilite/transition/assets/545502/7ba664b8-c49d-420f-8119-4fbf87955145)

Thoughts and suggestions @kaligrafy  @tahini ?

**Comment by greenscientist** [comment]
Just a thought, but also maybe with a possibility to clic on the unit to make it switch back and forth

**Comment by davidmurray** [comment]
Yeah, that could be useful too. I can make a React component that does that
