### ISSUE TITLE
Transit routing: 'walk' is always calculated even if not in the requested modes

### ISSUE THREAD

**Issue by davidmurray** [chairemobilite/transition#776]
![image](https://github.com/chairemobilite/transition/assets/545502/72f061cc-a81e-4fdd-92b1-8679f4e91022)

**Comment by tahini** [comment]
It is indeed on purpose, because we have to put in the alternatives the walk only option if less than 20 minutes. So, since we always calculate it anyway, we show it.

**Comment by davidmurray** [comment]
@tahini so should we remove it from the multi select at the top? Or at least have it by default and prevent removing it?
Otherwise it's a bit confusing to see 'walk' in the alternatives because it is not explicitly requested.
Minor issue though

**Comment by kaligrafy** [comment]
Yes we should auto activate it, and make it locked, and maybe add anexplanation why we always calculate it.

**Comment by tahini** [comment]
Or... we always need to calculate it (so we thought it was a good idea to always show it), but if the user does not explicitly asks to show it, we can hide it.

**Comment by tahini** [comment]
In fact, I don't know when this happened, but it is already the case that if you don't explicitly put the Walking mode in the choices, it does not show it, closing this
