### ISSUE TITLE
benchmark osrm calculation time depending on input osm file size

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/transition#87]
It should be the same in theory, but I would like to know if making the same request on the whole Quebec province network and on a small extract will result in the same calculation duration.

**Comment by greenscientist** [comment]
Did the benchmark. For about 4100 typical queries from Transition (in the Montreal area). The time was mostly constant. 
See: 
- MONTREAL: 11.609057s, 12.60829s, 171M Ram
- QUEBEC: 14.497788s, 12.486178s, 450M Ram
- CANADA: 13.912247s, 12.141368s, 1.7g Ram
