### ISSUE TITLE
sessions table seems to be created only the first time we use yarn start

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/transition#88]
the sessions table is not in the migrations (this is a table use by knex/express-sessions). this table should be created automatically but it seems if we only use yarn setup and yarn migrate, it is not created at that step. If we try to import a database dump just after these two commands (setup and migrate), the sessions table is missing and displays errors when importing. the sessions table should be created at setup or at migrate step, not  later on.

**Comment by tahini** [comment]
The session table is handled by the knex_session package itself and we should not touch it. Database backups and restores should come with the schema construction queries, in which case, we don't have to worry about it.
