### ISSUE TITLE
Scenarios: unable to exclude lines

### ISSUE THREAD

**Issue by davidmurray** [chairemobilite/transition#888]
The "excluded lines" field does not seem to have any effect. I can't exclude the line L1AH.
![image](https://github.com/chairemobilite/transition/assets/545502/89092368-fcd7-4126-a9c7-59cb1207539b)

Possible bug?

**Comment by tahini** [comment]
@davidmurray Can you check that the line is excluded in the routing calculations? It should be.

The bug you are showing here may actually be #667

**Comment by davidmurray** [comment]
Hi @tahini 
It's not being excluded 🙁 

![image](https://github.com/chairemobilite/transition/assets/545502/f58bc06f-1cd8-4f9c-95ba-72c3a20026cf)
![image](https://github.com/chairemobilite/transition/assets/545502/520e5d9b-68d0-43e9-9a54-c10ab7210cde)

Thanks

**Comment by greenscientist** [comment]
@tahini Do you think it's worth it to investitage on the trRouting side at this point or we should first confirm that the data is right from Transition first ?

**Comment by tahini** [comment]
I cannot reproduce this issue. I tried 2 scenarios, one excluding some lines and I really get different results for both scenarios. @davidmurray did you save the cache? Is it a local installation that you have (if so, is json2capnp started?)? or on one of the servers where I can test it?

**Comment by davidmurray** [comment]
> I cannot reproduce this issue. I tried 2 scenarios, one excluding some lines and I really get different results for both scenarios. @davidmurray did you save the cache? Is it a local installation that you have (if so, is json2capnp started?)? or on one of the servers where I can test it?

Sure 🙂 
It's on exo.transition.city
Service: CIRBEL_SEMAINE
Scenario: CITBEL test

**Comment by davidmurray** [comment]
Ça semble fonctionne en mettant à jour la cache (qui prend environ 2 minutes d'ailleurs).
J'ai toujours eu de la difficulté à comprendre quand devrais-je utiliser ces deux boutons:
![image](https://github.com/chairemobilite/transition/assets/545502/db992c5a-6ce1-48fe-9da3-af72a4bb4ccd)

Est-ce documenté quelque part?
Merci!

**Comment by tahini** [comment]
Je viens de tester, ça fonctionne en effet. C'est vrai que votre cache prend du temps à se sauvegarder. Il faut utiliser ces 2 boutons lorsqu'on fait des changements à des services/scénarios/lignes, etc. C'est pas super documenté car on aimerait mieux que ces boutons n'existent pas ;-) Un jour...

**Comment by tahini** [comment]
Tout fonctionne bien
