### ISSUE TITLE
It should not be possible to import nodes at the exact same location as another

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/transition#908]
even if the parameter says to not merge node on import in the GTFS import or any other node import tool.

**Comment by greenscientist** [comment]
@kaligrafy so what should  be the behavior ? Merging them anyway with a warning? Rejecting the operation? Adding a note to the node information ?

**Comment by kaligrafy** [comment]
Just merge. If the info is the same, just merge without warning, if there is mismmatch, we should warn the user with a popup saying:
Some nodes have the same coordinates as nodes already present, but with different attributes. What should we do with these attributes? [use imported attributes | use existing attributes | cancel]. Note that the cancel button could be quite complicated to process though.

**Comment by tahini** [comment]
I can reproduce this, for some GTFS with 200 nodes, 30 are constantly re-imported. It's because the nodes collection does not even detect them as within bird radius of each other. It works for the 170 others.

**Comment by tahini** [comment]
Turns out the local index, using geokdbush does not return those nodes when getting the nodes withing bird distance for those 30 repeated ones. If we use postgis instead, with st_dwithin, it works
