### ISSUE TITLE
pyTransition : SSLError when creating instance

### ISSUE THREAD

**Issue by tibobliss** [chairemobilite/transition#988]
I am using the Python library and trying to create a Transition instance from connection credentials. Here is what I use:

`transition_instance = Transition("https://instancename.transition.city", "email", "password")`

And here is the result I get every time:

`SSLError: HTTPSConnectionPool(host='stm.transition.city', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))`

**Comment by greenscientist** [comment]
@tibobliss , the first theory would be a lack on update on the operating system side.

**Comment by greenscientist** [comment]
Closing as this is a system issue, not due to the library

**Comment by tahini** [comment]
@greenscientist maybe an explanation of how it was solved could help people hitting this

**Comment by greenscientist** [comment]
People need to make sure they have the latest Root certificate list on their system to ensure that SSL works with every site. 
(I will not post here some work around, there's plenty on the rest of the internet :) )
