### ISSUE TITLE
pyTransition : Errors in sample code

### ISSUE THREAD

**Issue by tibobliss** [chairemobilite/transition#989]
Two errors cause issues when running the sample code for _request_accessibility_map_: 

- lat/long are inverted
- there is a trailing comma at the end of the parameters

![image](https://github.com/chairemobilite/transition/assets/5404176/a1c28469-d0f1-4a0a-af40-fd765d915e3a)

**Comment by greenscientist** [comment]
Also, those code example should be included in the README from external file so that we can CI test them.

**Comment by tibobliss** [comment]
Another one. In the two samples for connecting to the server, the get_nodes() function is used as an example. It is called in two different ways: `Transition.get_nodes()` and `transition_instance.get_nodes()`

![image](https://github.com/chairemobilite/transition/assets/5404176/fbff3b44-a045-4f6a-9dc3-6832df0b04ae)

The first one gives the following error:

`TypeError: Transition.get_nodes() missing 1 required positional argument: 'self'`

While the second one gives the following error:

`HTTPError: 500 Server Error: Internal Server Error for url: https://stmplanif.transition.city/api/v1/nodes`

So it seems that:

1. the second formulation should be used in all sample code
2. the get_nodes() function does not work properly

**Comment by greenscientist** [comment]
https://github.com/chairemobilite/transition/pull/1171 add a method to link actual script to the README to ease in testing. 
Some fixes were applied
